# We test each method for building LaTeX in a separate job.
language: generic

# Add distro
dist: xenian

# This is required to test texlive-docker because it searches for config options in this file
tex-config:
  - build-pattern=src/main.tex,src/mwe.tex
  - packages=xkeyval, collection-latex, collection-langeuropean, exam, amsmath, amscls, mathtools, thmtools, stmaryrd, xcolor, pdfpages, pgf, cancel, hyperref, pgfplots, listings, scalerel, stackengine, etoolbox, listofitems, marvosym, amsfonts, opensans, slantsc, fancyhdr, ulem, algorithms, algorithmicx, float, booktabs, enumitem, polynom, fancyvrb, makecmds, multirow, chngcntr, fvextra, upquote, lineno, ifplatform, xstring, framed, caption, collection-fontsrecommended, minted, pgfgantt, geometry, beamer, translator, environ, trimspaces, imakeidx, graphics, tools, oberdiek

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/miniconda
    - $HOME/.cache/Tectonic

jobs:
  include:
    # Each - starts a separate job
    - script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/tectonic-docker-test.sh && $TRAVIS_BUILD_DIR/test/tectonic-docker-test.sh
      name: "Run tectonic-docker-test"
    - script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/tectonic-miniconda-test.sh && $TRAVIS_BUILD_DIR/test/tectonic-miniconda-test.sh
      name: "Run tectonic-miniconda-test"
    - script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/texlive-docker-test.sh && $TRAVIS_BUILD_DIR/test/texlive-docker-test.sh
      name: "Run texlive-docker-test"
    - script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/texlive-docker-texliveonfly-test.sh && $TRAVIS_BUILD_DIR/test/texlive-docker-texliveonfly-test.sh
      name: "Run texlive-docker-texliveonfly"
    - before_install:
        - sudo apt-get install python-pygments
        - mkdir $HOME/.fonts
        - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
        - fc-cache -f -v
      script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/texlive-test.sh && $TRAVIS_BUILD_DIR/test/texlive-test.sh
      name: "Run texlive-test"

# Disable this test because it's broken and nobody uses it anyway
#    - stage: tinytex
#      language: r
#      sudo: true
#      latex: false
#      pandoc: false
#      warnings_are_errors: false
#      install: echo "The install step is required but does nothing now."
#      script: chmod +x $TRAVIS_BUILD_DIR/test/tinytex-test.sh && $TRAVIS_BUILD_DIR/test/tinytex-test.sh
#      cache:
#        directories:
#          - packages
#          - /tmp/texlive
#          - $HOME/.texlive
#          - $HOME/.TinyTex
